### ISSUE TITLE
`signInWithProvider` should return a UserCredential

### ISSUE THREAD

**Issue by guillaumearm** [ulentini/use-firebase-auth#2]
Hi, I noticed `createUserWithEmailAndPassword` and `signInWithEmailAndPassword` returns a firebase `UserCredential` but [`signInWithProvider` returns a regular `firebase.User`](https://github.com/ulentini/use-firebase-auth/blob/master/src/index.tsx#L137).

I need to get [`AdditionalUserInfo`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L116) from [`UserCredential`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth-types/index.d.ts#L269) when I login with google.

@ulentini: I will make a PR but this will be a breaking change, are you ok with that ?

**Comment by ulentini** [comment]
Closed by #3
